name: Pack Plugins
permissions: write-all
on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  pack-plugins:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        repository: breeze-shell/plugins
        path: source

    - name: Checkout target
      uses: actions/checkout@v4
      with:
        repository: breeze-shell/plugins-packed
        path: dist
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Run packaging script
      run: |
        mkdir -p dist/plugins
        node dist/pack-plugins.js

    - name: Commit and push
      working-directory: dist
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update plugins" && git push)
